repos:
  # Ruff  lint + autofix importów
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
      - id: ruff
        args: [--fix]

  # Pytest  uruchamia testy przed commitem (local hook)
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest -q
        language: system
        pass_filenames: false
