name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-type-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Configure Poetry (no venv)
        run: poetry config virtualenvs.create false

      - name: Cache Poetry downloads
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install project dependencies
        run: |
          if [ -f pyproject.toml ]; then
            poetry install --no-interaction --no-ansi
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No dependency file found"; exit 1
          fi

      # 👉 NIE używamy pre-commit w CI (unikanie buga virtualenv).
      #    Linty odpalamy bezpośrednio.
      - name: Lint (ruff)
        run: |
          poetry run python -m pip install ruff
          poetry run ruff check .

      - name: Type check (mypy)
        run: |
          python -m pip install mypy
          mypy --ignore-missing-imports --install-types --non-interactive src

      - name: Run tests (pytest)
        env:
          PYTHONWARNINGS: ignore::DeprecationWarning
        run: poetry run pytest -q
