name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-type-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Configure Poetry (no venv)
        run: poetry config virtualenvs.create false

      # ⬇⬇⬇ najważniejsze: NIE instalujemy grupy dev (czyli nie instalujemy pre-commit)
      - name: Install project dependencies (skip dev)
        run: poetry install --no-interaction --no-ansi --without dev

      # narzędzia CI doinstalowujemy przez pip (ruff, pytest, mypy)
      - name: Install CI tools
        run: |
          pip install ruff pytest pytest-cov mypy

      - name: Lint (ruff)
        run: ruff check .

      - name: Type check (mypy)
        run: mypy --ignore-missing-imports --install-types --non-interactive src

      - name: Run tests (pytest)
        env:
          PYTHONWARNINGS: ignore::DeprecationWarning
        run: pytest -q
